// <auto-generated />
using System;
using BeFit.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeFit.Migrations
{
    [DbContext(typeof(BeFitDbContext))]
    partial class BeFitDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeFit.Models.Cwiczenie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("NazwaCwiczenia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObciazenieKg")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Cwiczenia");
                });

            modelBuilder.Entity("BeFit.Models.SesjaTreningowa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUzytkownika")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("IdUzytkownika");

                    b.ToTable("SesjaTreningowa");
                });

            modelBuilder.Entity("BeFit.Models.Uzytkownicy", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uprawnienia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Uzytkownicy");
                });

            modelBuilder.Entity("BeFit.Models.Wynik", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("IdNazwyCwiczenia")
                        .HasColumnType("int");

                    b.Property<int>("IdSesjaTreningowa")
                        .HasColumnType("int");

                    b.Property<int>("LiczbaPowtorzenWSerii")
                        .HasColumnType("int");

                    b.Property<int>("LiczbaSerii")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("IdNazwyCwiczenia");

                    b.HasIndex("IdSesjaTreningowa");

                    b.ToTable("Wyniki");
                });

            modelBuilder.Entity("BeFit.Models.SesjaTreningowa", b =>
                {
                    b.HasOne("BeFit.Models.Uzytkownicy", "Uzytkownik")
                        .WithMany("ListaTreningow")
                        .HasForeignKey("IdUzytkownika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("BeFit.Models.Wynik", b =>
                {
                    b.HasOne("BeFit.Models.Cwiczenie", "NazwaCwiczenia")
                        .WithMany()
                        .HasForeignKey("IdNazwyCwiczenia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeFit.Models.SesjaTreningowa", "SesjaTreningowa")
                        .WithMany("CwiczeniaSesjiTreningowej")
                        .HasForeignKey("IdSesjaTreningowa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NazwaCwiczenia");

                    b.Navigation("SesjaTreningowa");
                });

            modelBuilder.Entity("BeFit.Models.SesjaTreningowa", b =>
                {
                    b.Navigation("CwiczeniaSesjiTreningowej");
                });

            modelBuilder.Entity("BeFit.Models.Uzytkownicy", b =>
                {
                    b.Navigation("ListaTreningow");
                });
#pragma warning restore 612, 618
        }
    }
}
